name: Pest - PHP Unit Testing

on:
  workflow_call:

jobs:
  pest:
    name: Pest (PHP v${{ matrix.php-versions }}) Unit Testing - Laravel v${{ matrix.laravel-versions }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ["8.2", "8.3", "8.4"]
        laravel-versions: ["11", "12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP (v${{ matrix.php-versions }})
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: swoole, dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: none

      - name: Install Composer Dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: |
            composer require "illuminate/support=^${{ matrix.laravel-versions }}" --no-update
            composer update --prefer-dist --no-interaction --no-progress
        continue-on-error: ${{ matrix.php-versions == '8.4' || matrix.laravel-versions == '12' }}

      - name: Pest PHP Unit Test
        run: vendor/bin/pest
        continue-on-error: ${{ matrix.php-versions == '8.4' || matrix.laravel-versions == '12' }}
